"use server";

import { revalidatePath } from "next/cache";
import type { LessonActionResult, LessonStatusOverride, ScheduleInput } from "@/components/students/student-lesson-types";
import { getCurrentProfile } from "@/lib/auth/get-current-profile";
import { addCalendarDays, almatyDate, almatyLocalToUtc } from "@/lib/lessons/lesson-generation";
import { createAdminClient } from "@/lib/supabase/admin";

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function log(label:string,error:{code?:string;message:string;details?:string;hint?:string}){console.error(label,{code:error.code,message:error.message,details:error.details,hint:error.hint});}
async function context(){const current=await getCurrentProfile();return current?.profile?.role==="ADMIN"?{profileId:current.profile.id,admin:createAdminClient()}:null;}
async function validStudent(admin:ReturnType<typeof createAdminClient>,studentId:string){const{data,error}=await admin.from("profiles").select("id").eq("id",studentId).eq("role","STUDENT").maybeSingle();return{ok:Boolean(data),error};}
async function ownedLesson(admin:ReturnType<typeof createAdminClient>,studentId:string,lessonId:string){return admin.from("student_lessons").select("id, starts_at, ends_at").eq("id",lessonId).eq("student_id",studentId).is("deleted_at",null).maybeSingle();}
function refresh(studentId:string){revalidatePath(`/admin/students/${studentId}`);revalidatePath("/admin");revalidatePath("/student");revalidatePath("/student/progress");}
async function reconcile(admin:ReturnType<typeof createAdminClient>,studentId:string){const result=await admin.rpc("reconcile_student_finance_atomic",{p_student_id:studentId});if(result.error&&result.error.code!=="PGRST202")log("Не удалось синхронизировать баланс:",result.error);}
function parseSlots(formData:FormData):ScheduleInput[]|null{try{const value=JSON.parse(String(formData.get("slots")??"[]")) as unknown;if(!Array.isArray(value))return null;return value.map((item)=>{const row=item as Partial<ScheduleInput>;return{weekday:Number(row.weekday),startTime:String(row.startTime??""),durationMinutes:Number(row.durationMinutes)}});}catch{return null;}}
function validateSlots(slots:ScheduleInput[]){const time=/^(?:[01]\d|2[0-3]):[0-5]\d$/;for(const slot of slots)if(!Number.isInteger(slot.weekday)||slot.weekday<1||slot.weekday>7||!time.test(slot.startTime)||!Number.isInteger(slot.durationMinutes)||slot.durationMinutes<15||slot.durationMinutes>300)return"Проверьте день, время и длительность занятий.";for(let i=0;i<slots.length;i+=1)for(let j=i+1;j<slots.length;j+=1)if(slots[i].weekday===slots[j].weekday){const startA=Number(slots[i].startTime.slice(0,2))*60+Number(slots[i].startTime.slice(3));const startB=Number(slots[j].startTime.slice(0,2))*60+Number(slots[j].startTime.slice(3));if(startA<startB+slots[j].durationMinutes&&startB<startA+slots[i].durationMinutes)return"Занятия в один день не должны пересекаться.";}return null;}

export async function saveStudentSchedule(studentId:string,formData:FormData):Promise<LessonActionResult>{const ctx=await context();if(!ctx)return{ok:false,message:"Недостаточно прав."};if(!uuid.test(studentId))return{ok:false,message:"Некорректный ученик."};const student=await validStudent(ctx.admin,studentId);if(student.error){log("Не удалось проверить ученика:",student.error);return{ok:false,message:"Не удалось проверить ученика."};}if(!student.ok)return{ok:false,message:"Ученик не найден."};const slots=parseSlots(formData);if(!slots)return{ok:false,message:"Некорректное расписание."};const validation=validateSlots(slots);if(validation)return{ok:false,message:validation};const effective=almatyDate();const{error}=await ctx.admin.rpc("replace_student_schedule_and_lessons_atomic",{p_student_id:studentId,p_created_by:ctx.profileId,p_effective_from:effective,p_slots:slots,p_generate_through:addCalendarDays(effective,31)});if(error){log("Не удалось атомарно заменить расписание и уроки:",error);return{ok:false,message:"Не удалось сохранить расписание."};}refresh(studentId);return{ok:true,message:"Расписание обновлено"};}

export async function setFutureLessonStatus(studentId:string,lessonId:string,value:string):Promise<LessonActionResult>{const ctx=await context();if(!ctx)return{ok:false,message:"Недостаточно прав."};if(!uuid.test(studentId)||!uuid.test(lessonId))return{ok:false,message:"Некорректные данные урока."};const lesson=await ownedLesson(ctx.admin,studentId,lessonId);if(lesson.error){log("Не удалось проверить урок:",lesson.error);return{ok:false,message:"Не удалось проверить урок."};}if(!lesson.data)return{ok:false,message:"Урок не найден."};if(new Date(lesson.data.ends_at)<=new Date())return{ok:false,message:"Урок уже завершён."};const status:LessonStatusOverride|null=value==="SCHEDULED"?null:value==="CANCELLED_BY_TEACHER"||value==="CANCELLED_BY_STUDENT"?value:null;if(value!=="SCHEDULED"&&!status)return{ok:false,message:"Некорректный статус урока."};const{error}=await ctx.admin.from("student_lessons").update({status_override:status,updated_at:new Date().toISOString()}).eq("id",lessonId).eq("student_id",studentId);if(error){log("Не удалось изменить отмену урока:",error);return{ok:false,message:"Не удалось изменить статус урока."};}refresh(studentId);return{ok:true,message:"Статус урока обновлён"};}

export async function setLessonAttendance(studentId:string,lessonId:string,value:string):Promise<LessonActionResult>{const ctx=await context();if(!ctx)return{ok:false,message:"Недостаточно прав."};if(!uuid.test(studentId)||!uuid.test(lessonId))return{ok:false,message:"Некорректные данные урока."};const lesson=await ownedLesson(ctx.admin,studentId,lessonId);if(lesson.error||!lesson.data){if(lesson.error)log("Не удалось проверить урок:",lesson.error);return{ok:false,message:"Урок не найден."};}if(new Date(lesson.data.ends_at)>new Date())return{ok:false,message:"Урок ещё не завершён."};const status:LessonStatusOverride|null=value==="ATTENDED"?null:value==="NO_SHOW"||value==="LATE_CANCELLED"?value:null;if(value!=="ATTENDED"&&!status)return{ok:false,message:"Некорректная посещаемость."};const{error}=await ctx.admin.from("student_lessons").update({status_override:status,updated_at:new Date().toISOString()}).eq("id",lessonId).eq("student_id",studentId);if(error){log("Не удалось сохранить посещаемость:",error);return{ok:false,message:"Не удалось сохранить посещаемость."};}await reconcile(ctx.admin,studentId);refresh(studentId);return{ok:true,message:"Посещаемость обновлена"};}

export async function saveLessonHomework(studentId:string,lessonId:string,formData:FormData):Promise<LessonActionResult>{const ctx=await context();if(!ctx)return{ok:false,message:"Недостаточно прав."};if(!uuid.test(studentId)||!uuid.test(lessonId))return{ok:false,message:"Некорректные данные урока."};const lesson=await ownedLesson(ctx.admin,studentId,lessonId);if(lesson.error||!lesson.data){if(lesson.error)log("Не удалось проверить урок:",lesson.error);return{ok:false,message:"Урок не найден."};}const title=String(formData.get("title")??"").trim(),comment=String(formData.get("comment")??"").trim()||null,gradeRaw=String(formData.get("grade")??"").trim();const grade=gradeRaw===""?null:Number(gradeRaw);if(!title||title.length>200)return{ok:false,message:"Название ДЗ обязательно и не должно превышать 200 символов."};if(comment&&comment.length>500)return{ok:false,message:"Комментарий не должен превышать 500 символов."};if(grade!==null&&(!Number.isInteger(grade)||grade<0||grade>10))return{ok:false,message:"Оценка должна быть от 0 до 10."};const{error}=await ctx.admin.from("lesson_homework_records").upsert({lesson_id:lessonId,student_id:studentId,title,grade,comment,created_by:ctx.profileId,updated_at:new Date().toISOString()},{onConflict:"lesson_id"});if(error){log("Не удалось сохранить ДЗ:",error);return{ok:false,message:"Не удалось сохранить ДЗ."};}refresh(studentId);return{ok:true,message:"ДЗ сохранено"};}

export async function deleteLessonHomework(studentId:string,lessonId:string):Promise<LessonActionResult>{const ctx=await context();if(!ctx)return{ok:false,message:"Недостаточно прав."};if(!uuid.test(studentId)||!uuid.test(lessonId))return{ok:false,message:"Некорректные данные урока."};const lesson=await ownedLesson(ctx.admin,studentId,lessonId);if(lesson.error||!lesson.data){if(lesson.error)log("Не удалось проверить урок:",lesson.error);return{ok:false,message:"Урок не найден."};}const{error}=await ctx.admin.from("lesson_homework_records").delete().eq("lesson_id",lessonId).eq("student_id",studentId);if(error){log("Не удалось удалить ДЗ:",error);return{ok:false,message:"Не удалось удалить ДЗ."};}refresh(studentId);return{ok:true,message:"Запись ДЗ удалена"};}

export async function createDevPastLesson(studentId:string):Promise<LessonActionResult>{if(process.env.NODE_ENV!=="development")return{ok:false,message:"Тестовые уроки доступны только в development."};const ctx=await context();if(!ctx)return{ok:false,message:"Недостаточно прав."};if(!uuid.test(studentId))return{ok:false,message:"Некорректный ученик."};const student=await validStudent(ctx.admin,studentId);if(student.error){log("Не удалось проверить ученика для тестового урока:",student.error);return{ok:false,message:"Не удалось проверить ученика."};}if(!student.ok)return{ok:false,message:"Ученик не найден."};const yesterday=addCalendarDays(almatyDate(),-1),start=almatyLocalToUtc(yesterday,"18:00"),end=almatyLocalToUtc(yesterday,"19:00");const{data:existing,error:findError}=await ctx.admin.from("student_lessons").select("id").eq("student_id",studentId).eq("starts_at",start.toISOString()).maybeSingle();if(findError){log("Не удалось проверить тестовый урок:",findError);return{ok:false,message:"Не удалось проверить существующий урок."};}if(existing)return{ok:false,message:"Урок на вчера в 18:00 уже существует."};const{error}=await ctx.admin.from("student_lessons").insert({student_id:studentId,schedule_slot_id:null,starts_at:start.toISOString(),ends_at:end.toISOString(),status_override:null});if(error){if(error.code==="23505")return{ok:false,message:"Урок на вчера в 18:00 уже существует."};log("Не удалось создать тестовый урок:",error);return{ok:false,message:"Не удалось создать тестовый урок."};}refresh(studentId);return{ok:true,message:"Тестовый прошедший урок создан"};}

export async function deleteDevPastLesson(studentId:string,lessonId:string):Promise<LessonActionResult>{if(process.env.NODE_ENV!=="development")return{ok:false,message:"Удаление тестового урока доступно только в development."};const ctx=await context();if(!ctx)return{ok:false,message:"Недостаточно прав."};if(!uuid.test(studentId)||!uuid.test(lessonId))return{ok:false,message:"Некорректные данные урока."};const{data,error:findError}=await ctx.admin.from("student_lessons").select("id, schedule_slot_id").eq("id",lessonId).eq("student_id",studentId).maybeSingle();if(findError){log("Не удалось проверить тестовый урок перед удалением:",findError);return{ok:false,message:"Не удалось проверить урок."};}if(!data)return{ok:false,message:"Урок не найден."};if(data.schedule_slot_id!==null)return{ok:false,message:"Можно удалить только тестовый урок без расписания."};const{error}=await ctx.admin.from("student_lessons").delete().eq("id",lessonId).eq("student_id",studentId).is("schedule_slot_id",null);if(error){log("Не удалось удалить тестовый урок:",error);return{ok:false,message:"Не удалось удалить тестовый урок."};}refresh(studentId);return{ok:true,message:"Тестовый урок удалён"};}

export async function deletePastLesson(studentId:string,lessonId:string):Promise<LessonActionResult>{const ctx=await context();if(!ctx)return{ok:false,message:"Недостаточно прав."};if(!uuid.test(studentId)||!uuid.test(lessonId))return{ok:false,message:"Некорректные данные урока."};const lesson=await ownedLesson(ctx.admin,studentId,lessonId);if(lesson.error){log("Не удалось проверить урок перед удалением:",lesson.error);return{ok:false,message:"Не удалось проверить урок."};}if(!lesson.data)return{ok:false,message:"Урок не найден."};if(new Date(lesson.data.ends_at)>new Date())return{ok:false,message:"Будущий урок удалить нельзя."};const{data,error}=await ctx.admin.rpc("soft_delete_student_lesson",{p_student_id:studentId,p_lesson_id:lessonId});if(error){log("Не удалось удалить прошедший урок:",error);return{ok:false,message:"Не удалось удалить урок."};}if(data!==true)return{ok:false,message:"Урок уже удалён или ещё не завершён."};await reconcile(ctx.admin,studentId);refresh(studentId);return{ok:true,message:"Урок удалён"};}
