"use client";

import { useMemo,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import LibrarySortMenu from "@/components/admin/library-sort-menu";
import MaterialLibraryContent from "@/components/materials/material-library-content";
import type { MaterialFolderItem } from "@/components/materials/material-folder-card";
import type { MaterialLibraryFolder,MaterialLibraryItem } from "@/lib/materials/load-material-library";
import { sortLibraryItems,type LibrarySort,withSort } from "@/lib/library-sort";
import { releasePending,tryAcquirePending } from "@/lib/ui/pending-guard";
import { deleteMaterialFolder,inspectMaterialFolderDeletion,moveMaterialFolder,renameMaterialFolder,type ActionResult,type MaterialFolderActionResult } from "./actions";
import MaterialCreatePanel from "./material-create-panel";
import styles from "./materials.module.css";

type Modal={kind:"rename"|"move"|"delete";folder:MaterialFolderItem}|null;
export default function MaterialLibraryExplorer({initialFolderId,initialFolders,initialMaterials,sort}:{initialFolderId:string|null;initialFolders:MaterialLibraryFolder[];initialMaterials:MaterialLibraryItem[];sort:LibrarySort}){
  const router=useRouter();
  const[folderId,setFolderId]=useState(initialFolderId),[folders,setFolders]=useState(initialFolders),[materials,setMaterials]=useState(initialMaterials),[modal,setModal]=useState<Modal>(null),[name,setName]=useState(""),[destination,setDestination]=useState(""),[confirmation,setConfirmation]=useState(""),[result,setResult]=useState<MaterialFolderActionResult|null>(null),[pending,setPending]=useState(false),[recentId,setRecentId]=useState<string|null>(null),pendingGuard=useRef(false);
  const byId=useMemo(()=>new Map(folders.map(folder=>[folder.id,folder])),[folders]);
  const chain=useMemo(()=>{const items:MaterialLibraryFolder[]=[];const seen=new Set<string>();let id=folderId;while(id&&!seen.has(id)){seen.add(id);const folder=byId.get(id);if(!folder)break;items.unshift(folder);id=folder.parentId;}return items;},[byId,folderId]);
  const current=folderId?byId.get(folderId):null;
  const children=useMemo(()=>promoteRecent(sortLibraryItems(folders.filter(folder=>folder.parentId===folderId),sort,item=>item.name,item=>item.createdAt),recentId),[folderId,folders,recentId,sort]);
  const visible=useMemo(()=>promoteRecent(sortLibraryItems(materials.filter(material=>material.folderId===folderId),sort,item=>item.title,item=>item.created_at),recentId),[folderId,materials,recentId,sort]);
  const counts=(folder:MaterialLibraryFolder):MaterialFolderItem=>({...folder,childFolderCount:folders.filter(item=>item.parentId===folder.id).length,materialCount:materials.filter(item=>item.folderId===folder.id).length});
  const navigate=(id:string|null,replace=false)=>{const href=withSort(id?`/admin/materials/folders/${id}`:"/admin/materials",sort);setFolderId(id);setRecentId(null);setModal(null);if(replace)router.replace(href,{scroll:false});else router.push(href,{scroll:false});};
  const descendants=(id:string)=>{const found=new Set<string>();const visit=(parent:string)=>folders.filter(item=>item.parentId===parent).forEach(item=>{if(!found.has(item.id)){found.add(item.id);visit(item.id);}});visit(id);return found;};
  const closeModal=()=>{if(!pendingGuard.current)setModal(null);};
  const runFolderAction=async(action:()=>Promise<MaterialFolderActionResult>)=>{if(!tryAcquirePending(pendingGuard))return null;setPending(true);try{return await action();}catch{return{ok:false,message:"Не удалось выполнить действие с папкой."};}finally{releasePending(pendingGuard);setPending(false);}};
  const openAction=async(kind:"rename"|"move"|"delete",folder:MaterialFolderItem)=>{if(pendingGuard.current)return;setModal({kind,folder});setName(folder.name);setDestination(folder.parentId??"");setConfirmation("");setResult(null);if(kind==="delete"){const response=await runFolderAction(()=>inspectMaterialFolderDeletion(folder.id));if(response)setResult(response);}};
  const rename=async()=>{if(!modal)return;const current=modal,response=await runFolderAction(()=>renameMaterialFolder(current.folder.id,name));if(!response)return;setResult(response);if(response.ok){setFolders(items=>items.map(item=>item.id===current.folder.id?{...item,name:name.trim()}:item));setModal(null);}};
  const move=async()=>{if(!modal)return;const current=modal,parentId=destination||null,response=await runFolderAction(()=>moveMaterialFolder(current.folder.id,parentId));if(!response)return;setResult(response);if(response.ok){setFolders(items=>items.map(item=>item.id===current.folder.id?{...item,parentId}:item));setModal(null);}};
  const remove=async()=>{if(!modal)return;const current=modal,response=await runFolderAction(()=>deleteMaterialFolder(current.folder.id,confirmation));if(!response)return;setResult(response);if(response.ok){const removed=descendants(current.folder.id);removed.add(current.folder.id);setFolders(items=>items.filter(item=>!removed.has(item.id)));setMaterials(items=>items.filter(item=>!item.folderId||!removed.has(item.folderId)));if(response.storageErrors?.length)return;setModal(null);}};
  const created=(response:ActionResult)=>{if(!response.ok||!response.item)return;const item=response.item;setRecentId(item.id);if(item.kind==="folder")setFolders(items=>[...items,{id:item.id,parentId:item.parentId,name:item.name,createdAt:item.createdAt}]);else setMaterials(items=>[...items,{id:item.id,folderId:item.parentId,type:item.type??"TEXT",title:item.name,description:null,file_size:null,external_url:null,created_at:item.createdAt,signedUrl:null}]);};
  const blocked=modal?descendants(modal.folder.id):new Set<string>();
  const breadcrumb=<><button type="button" onClick={()=>navigate(null)}>Материалы</button>{chain.map((item,index)=><span className={styles.breadcrumbItem} key={item.id}><span aria-hidden="true">/</span>{index===chain.length-1?<span aria-current="page">{item.name}</span>:<button type="button" onClick={()=>navigate(item.id)}>{item.name}</button>}</span>)}</>;
  return <><MaterialCreatePanel currentFolderId={folderId} title={current?.name??"Материалы"} subtitle={current?"Содержимое текущей папки.":"Файлы, ссылки, видео и тексты в одной библиотеке."} breadcrumb={breadcrumb} onBack={current?()=>navigate(current.parentId):undefined} onCreated={created}><LibrarySortMenu value={sort}/><MaterialLibraryContent folders={children.map(counts)} materials={visible} emptyText={current?"В этой папке пока нет подпапок и материалов":"Создайте первую папку или добавьте материал"} sort={sort} onNavigate={navigate} onFolderAction={openAction}/></MaterialCreatePanel>
  {modal&&<div className={styles.modalBackdrop} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)closeModal();}}><section className={styles.folderDialog} role="dialog" aria-modal="true" aria-labelledby="material-folder-dialog" aria-busy={pending} onKeyDown={event=>{if(event.key!=="Escape")return;if(pendingGuard.current){event.preventDefault();event.stopPropagation();}else closeModal();}}><h2 id="material-folder-dialog">{modal.kind==="rename"?"Переименовать папку":modal.kind==="move"?"Переместить папку":`Удалить «${modal.folder.name}»`}</h2>{modal.kind==="rename"&&<label>Название<input autoFocus value={name} onChange={event=>setName(event.target.value)}/></label>}{modal.kind==="move"&&<label>Новая родительская папка<select autoFocus value={destination} onChange={event=>setDestination(event.target.value)}><option value="">Материалы (корень)</option>{folders.filter(item=>item.id!==modal.folder.id&&!blocked.has(item.id)).map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>}{modal.kind==="delete"&&<>{pending&&<p>Проверяем содержимое…</p>}{result?.summary&&<p>Будет удалено: {result.summary.descendantFolders} вложенных папок и {result.summary.materials} материалов.</p>}{result?.ok&&<label>Введите УДАЛИТЬ<input autoFocus value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label>}{result?.storageErrors?.length&&<div className={styles.storageError}><strong>Папка удалена из базы, но Storage очищен не полностью:</strong>{result.storageErrors.map((message,index)=><p key={index}>{message}</p>)}</div>}</>}{result&&!result.ok&&<p className={styles.formError} role="alert">{result.message}</p>}<div className={styles.dialogActions}>{modal.kind==="rename"&&<button className={styles.primaryButton} disabled={pending||!name.trim()} onClick={rename}>Сохранить</button>}{modal.kind==="move"&&<button className={styles.primaryButton} disabled={pending} onClick={move}>Переместить</button>}{modal.kind==="delete"&&<button className={styles.dangerButton} disabled={pending||confirmation!=="УДАЛИТЬ"} onClick={remove}>{pending?"Удаляем…":"Удалить"}</button>}<button className={styles.secondaryButton} disabled={pending} onClick={closeModal}>Отмена</button></div></section></div>}</>;
}

function promoteRecent<T extends {id:string}>(items:T[],recentId:string|null){if(!recentId)return items;const index=items.findIndex(item=>item.id===recentId);if(index<=0)return items;return[items[index],...items.slice(0,index),...items.slice(index+1)];}
