"use client";

import Link from "next/link";
import { useEffect, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { THEORY_CHATGPT_INSTRUCTION } from "@/lib/trainers/theory-chatgpt-instruction";
import type { TheoryDefinition, TheoryStatus } from "@/lib/trainers/theory-types";
import { releasePending, tryAcquirePending } from "@/lib/ui/pending-guard";
import { createTheoryDraft, deleteTheoryTrainer, previewTheoryImport, renameTheoryTrainer } from "./actions";
import styles from "../trainers.module.css";
import studentStyles from "@/app/student/trainers/trainers.module.css";
import {CreateGroupButton,MoveTrainerButton,TrainerGroupSection} from "@/components/trainers/trainer-group-ui";
import {groupTrainerItems,type TrainerGroup} from "@/lib/trainers/trainer-groups";

type Item = { id: string; title: string; status: TheoryStatus; questionCount: number; updatedAt: string;groupId:string|null };
function Modal({ title, close, pending, children }: { title: string; close: () => void; pending: boolean; children: React.ReactNode }) { return <div className={styles.backdrop} onMouseDown={(event) => { if (event.target === event.currentTarget && !pending) close(); }}><section className={styles.dialog} role="dialog" aria-modal="true" aria-label={title} aria-busy={pending} onKeyDown={(event) => { if (event.key !== "Escape") return; if (pending) { event.preventDefault(); event.stopPropagation(); } else close(); }}><header><h2>{title}</h2><button className={styles.close} onClick={close} disabled={pending} aria-label="Закрыть">×</button></header>{children}</section></div>; }

function ImportDialog({ close,groups }: { close: () => void;groups:TrainerGroup[] }) {
  const router = useRouter(); const [raw, setRaw] = useState(""); const [errors, setErrors] = useState<string[]>([]); const [preview, setPreview] = useState<TheoryDefinition | null>(null); const [copy, setCopy] = useState("Инструкция для ChatGPT"); const [pending, start] = useTransition();const[groupId,setGroupId]=useState(""); const pendingGuard=useRef(false);
  useEffect(() => { if (copy === "Инструкция для ChatGPT") return; const timer = setTimeout(() => setCopy("Инструкция для ChatGPT"), 1800); return () => clearTimeout(timer); }, [copy]);
  const copyInstruction = async () => { try { await navigator.clipboard.writeText(THEORY_CHATGPT_INSTRUCTION); setCopy("Скопировано"); } catch { setCopy("Не удалось скопировать"); } };
  const safeClose=()=>{if(!pendingGuard.current)close();};
  const check = () => { if(!tryAcquirePending(pendingGuard))return; start(async () => { try { const result = await previewTheoryImport(raw); if (result.ok) { setPreview(result.definition as TheoryDefinition); setErrors([]); } else { setPreview(null); setErrors(result.errors ?? [result.message]); } } catch { setPreview(null); setErrors(["Не удалось проверить импорт."]); } finally { releasePending(pendingGuard); } }); };
  const create = () => { if(!tryAcquirePending(pendingGuard))return; start(async () => { try { const result = await createTheoryDraft(raw,groupId||null); if (result.ok) { if (result.trainerId) router.push(`/admin/trainers/theory/${result.trainerId}`); else setErrors([result.message]); } else setErrors(result.errors ?? [result.message]); } catch { setErrors(["Не удалось создать черновик."]); } finally { releasePending(pendingGuard); } }); };
  return <Modal title="Импорт Theory" close={safeClose} pending={pending}><div className={styles.instructionRow}><button className={styles.secondary} onClick={copyInstruction} aria-live="polite">{copy}</button></div><label className={styles.textareaLabel} htmlFor="theory-import">Вставьте NSP_THEORY_IMPORT_V1 JSON:</label><textarea id="theory-import" value={raw} onChange={(event) => { setRaw(event.target.value); setPreview(null); setErrors([]); }} placeholder="Вставьте JSON" disabled={pending}/><div className={styles.dialogActions}><button className={styles.primary} onClick={check} disabled={pending || !raw.trim()}>{pending ? "Проверяем…" : "Проверить"}</button><button className={styles.secondary} onClick={safeClose} disabled={pending}>Отмена</button></div>{errors.length > 0 && <div className={styles.errors} role="alert"><ul>{errors.map((error) => <li key={error}>{error}</li>)}</ul></div>}{preview && <div className={styles.preview}><div className={styles.previewSummary}><div><small>Название</small><strong>{preview.title}</strong></div><div><small>Вопросов</small><strong>{preview.questions.length}</strong></div></div><label className={styles.textareaLabel}>Тема<select value={groupId} onChange={e=>setGroupId(e.target.value)}><option value="">Без темы</option>{groups.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label><button className={styles.primary} onClick={create} disabled={pending}>{pending ? "Создаём…" : "Создать черновик"}</button></div>}</Modal>;
}

function RenameDialog({ item, close }: { item: Item; close: () => void }) { const router = useRouter(); const [title, setTitle] = useState(item.title); const [message, setMessage] = useState(""); const [pending, start] = useTransition(); const pendingGuard=useRef(false);const safeClose=()=>{if(!pendingGuard.current)close();};const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!tryAcquirePending(pendingGuard))return;start(async()=>{try{const result=await renameTheoryTrainer(item.id,title);setMessage(result.message);if(result.ok){close();router.refresh();}}catch{setMessage("Не удалось переименовать Theory.");}finally{releasePending(pendingGuard);}})};return <Modal title="Переименовать Theory" close={safeClose} pending={pending}><form className={styles.renameForm} onSubmit={submit} aria-busy={pending}><label>Название<input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={120} disabled={pending}/></label>{message && <p className={styles.renameError} role="alert">{message}</p>}<div className={styles.renameActions}><button className={styles.secondary} type="button" onClick={safeClose} disabled={pending}>Отмена</button><button className={styles.primary} disabled={pending}>{pending?"Сохраняем…":"Сохранить"}</button></div></form></Modal>; }
function DeleteDialog({ item, close }: { item: Item; close: () => void }) { const router = useRouter(); const [confirmation, setConfirmation] = useState(""); const [message, setMessage] = useState(""); const [pending, start] = useTransition();const pendingGuard=useRef(false);const safeClose=()=>{if(!pendingGuard.current)close();};const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(confirmation!=="DELETE"||!tryAcquirePending(pendingGuard))return;start(async()=>{try{const result=await deleteTheoryTrainer(item.id,confirmation);setMessage(result.message);if(result.ok){close();router.refresh();}}catch{setMessage("Не удалось удалить Theory.");}finally{releasePending(pendingGuard);}})};return <Modal title="Удалить Theory?" close={safeClose} pending={pending}><p>Тренажёр «{item.title}» будет удалён.</p><form className={styles.renameForm} onSubmit={submit} aria-busy={pending}><label>Введите DELETE<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="off" disabled={pending}/></label>{message && <p className={styles.renameError} role="alert">{message}</p>}<div className={styles.renameActions}><button className={styles.secondary} type="button" onClick={safeClose} disabled={pending}>Отмена</button><button className={styles.confirmDelete} disabled={pending || confirmation !== "DELETE"}>{pending?"Удаляем…":"Удалить"}</button></div></form></Modal>; }

export default function TheoryLibrary({ trainers,groups, loadError }: { trainers: Item[];groups:TrainerGroup[]; loadError: boolean }) {
  const [importOpen, setImportOpen] = useState(false); const [rename, setRename] = useState<Item | null>(null); const [remove, setRemove] = useState<Item | null>(null);
  const grouped=groupTrainerItems(groups,trainers,true);const card=(item:Item)=><article className={`${studentStyles.trainerRow} ${styles.adminTrainerRow}`} key={item.id}><div className={studentStyles.trainerRowHeading}><h3>{item.title}</h3></div><p className={styles.trainerMetadata}>Вопросов: <strong>{item.questionCount}</strong><span>·</span><b className={item.status === "PUBLISHED" ? styles.publishedStatus : styles.draftStatus}>{item.status === "PUBLISHED" ? "Опубликован" : "Черновик"}</b></p><div className={styles.adminTrainerActions}><Link className={styles.rowPrimary} href={`/admin/trainers/theory/${item.id}`}>Редактировать</Link><MoveTrainerButton trainerId={item.id} title={item.title} currentGroupId={item.groupId} groups={groups}/><button className={styles.rowSecondary} onClick={() => setRename(item)}>Переименовать</button><button className={styles.rowDelete} onClick={() => setRemove(item)}>Удалить</button></div></article>;
  return <><header className={`${studentStyles.quickProblemsPageHero} ${studentStyles.theoryPageHero}`}><div className={studentStyles.quickProblemsHeroContent}><span>Тренажёры</span><h1>Theory</h1><p>Теоретические тренажёры по темам</p><div className={styles.heroActionSlot}><div className={styles.headerActions}><CreateGroupButton trainerType="THEORY"/><button className={styles.primary} onClick={() => setImportOpen(true)}>Импортировать</button></div></div></div></header>{loadError?<p className={styles.error}>Не удалось загрузить Theory.</p>:<section className={studentStyles.trainerList}>{grouped.map((group,index)=><TrainerGroupSection key={group.id??"ungrouped"} title={group.title} count={group.items.length} adminGroup={group.id?groups.find(g=>g.id===group.id):undefined} canMoveUp={group.id!==null&&index>0} canMoveDown={group.id!==null&&index<groups.length-1}>{group.items.length?group.items.map(card):<p className={styles.empty}>В этой теме пока нет Theory.</p>}</TrainerGroupSection>)}</section>}{importOpen && <ImportDialog groups={groups} close={() => setImportOpen(false)}/>} {rename && <RenameDialog item={rename} close={() => setRename(null)}/>} {remove && <DeleteDialog item={remove} close={() => setRemove(null)}/>}</>;
}
