"use client";

import { useRef,useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { createTrainerGroup,deleteTrainerGroup,moveTrainerGroup,moveTrainerToGroup,renameTrainerGroup } from "@/app/admin/trainers/group-actions";
import type { TrainerGroup,TrainerGroupType } from "@/lib/trainers/trainer-groups";
import { releasePending,tryAcquirePending } from "@/lib/ui/pending-guard";
import styles from "./trainer-groups.module.css";

export function TrainerGroupSection({title,count,progressPercent,adminGroup,canMoveUp=false,canMoveDown=false,children,defaultOpen=false}:{title:string;count:number;progressPercent?:number;adminGroup?:TrainerGroup;canMoveUp?:boolean;canMoveDown?:boolean;children:React.ReactNode;defaultOpen?:boolean}){
 const [edit,setEdit]=useState<"rename"|"delete"|null>(null);
 const [expanded,setExpanded]=useState(defaultOpen);
 const [moving,startMove]=useTransition();
 const router=useRouter();
 const move=(direction:-1|1)=>adminGroup&&startMove(async()=>{const result=await moveTrainerGroup(adminGroup.id,adminGroup.trainerType,direction);if(result.ok)router.refresh()});
 return <section className={`${styles.group} ${expanded?styles.expanded:""}`}><div className={styles.groupHeader}><button type="button" className={`${styles.summary} ${progressPercent!==undefined?styles.studentSummary:""}`} aria-expanded={expanded} onClick={()=>setExpanded(value=>!value)}><strong>{title}</strong>{progressPercent===undefined?<span>{count}</span>:<div className={styles.topicProgress}><span>{progressPercent}%</span><div className={styles.progress}><i style={{width:`${progressPercent}%`}}/></div></div>}</button>{adminGroup&&<div className={styles.orderActions} aria-label={`Порядок темы «${title}»`}><button type="button" aria-label={`Переместить тему «${title}» вверх`} title="Переместить вверх" disabled={moving||!canMoveUp} onClick={()=>move(-1)}>↑</button><button type="button" aria-label={`Переместить тему «${title}» вниз`} title="Переместить вниз" disabled={moving||!canMoveDown} onClick={()=>move(1)}>↓</button></div>}</div>{expanded&&<div className={styles.body}>{adminGroup&&<div className={styles.actions}><button onClick={()=>setEdit("rename")}>Переименовать тему</button><button className={styles.danger} onClick={()=>setEdit("delete")}>Удалить тему</button></div>}{children}</div>}{edit&&<GroupEditDialog group={adminGroup!} mode={edit} close={()=>setEdit(null)}/>}</section>;
}

export function CreateGroupButton({trainerType}:{trainerType:TrainerGroupType}){const [open,setOpen]=useState(false);return <>{<button className={styles.create} onClick={()=>setOpen(true)}>+ Создать тему</button>}{open&&<GroupCreateDialog trainerType={trainerType} close={()=>setOpen(false)}/>}</>}

function GroupCreateDialog({trainerType,close}:{trainerType:TrainerGroupType;close:()=>void}){const router=useRouter();const [title,setTitle]=useState("");const [error,setError]=useState("");const [pending,start]=useTransition();const guard=useRef(false);const safeClose=()=>{if(!guard.current)close()};const submit=()=>{if(!tryAcquirePending(guard))return;start(async()=>{try{const r=await createTrainerGroup(trainerType,title);if(r.ok){close();router.refresh();}else setError(r.message)}catch{setError("Не удалось создать тему.")}finally{releasePending(guard)}})};return <Dialog title="Создать тему" close={safeClose} pending={pending}><label>Название темы<input value={title} maxLength={120} autoFocus disabled={pending} onChange={e=>setTitle(e.target.value)}/></label>{error&&<p className={styles.error} role="alert">{error}</p>}<footer><button disabled={pending} onClick={safeClose}>Отмена</button><button className={styles.primary} disabled={pending||!title.trim()} onClick={submit}>{pending?"Создаём…":"Создать"}</button></footer></Dialog>}
function GroupEditDialog({group,mode,close}:{group:TrainerGroup;mode:"rename"|"delete";close:()=>void}){const router=useRouter();const [title,setTitle]=useState(group.title);const [error,setError]=useState("");const [pending,start]=useTransition();const guard=useRef(false);const safeClose=()=>{if(!guard.current)close()};const submit=()=>{if(!tryAcquirePending(guard))return;start(async()=>{try{const r=mode==="rename"?await renameTrainerGroup(group.id,group.trainerType,title):await deleteTrainerGroup(group.id,group.trainerType);if(r.ok){close();router.refresh();}else setError(r.message)}catch{setError(mode==="delete"?"Не удалось удалить тему.":"Не удалось переименовать тему.")}finally{releasePending(guard)}})};return <Dialog title={mode==="rename"?"Переименовать тему":"Удалить тему"} close={safeClose} pending={pending}>{mode==="rename"?<label>Название темы<input value={title} maxLength={120} disabled={pending} onChange={e=>setTitle(e.target.value)}/></label>:<p>Удалить тему «{group.title}»? Все тренажёры из этой темы будут перемещены в «Без темы».</p>}{error&&<p className={styles.error} role="alert">{error}</p>}<footer><button disabled={pending} onClick={safeClose}>Отмена</button><button className={styles.primary} disabled={pending} onClick={submit}>{pending?mode==="delete"?"Удаляем…":"Сохраняем…":mode==="rename"?"Сохранить":"Удалить тему"}</button></footer></Dialog>}
function Dialog({title,close,pending,children}:{title:string;close:()=>void;pending:boolean;children:React.ReactNode}){return <div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget&&!pending)close()}}><section className={styles.dialog} role="dialog" aria-modal="true" aria-label={title} aria-busy={pending} onKeyDown={event=>{if(event.key!=="Escape")return;if(pending){event.preventDefault();event.stopPropagation()}else close()}}><h2>{title}</h2>{children}</section></div>}

export function MoveTrainerButton({trainerId,title,currentGroupId,groups}:{trainerId:string;title:string;currentGroupId:string|null;groups:TrainerGroup[]}){const router=useRouter();const [open,setOpen]=useState(false);const [groupId,setGroupId]=useState(currentGroupId??"");const [error,setError]=useState("");const [pending,start]=useTransition();const guard=useRef(false);const close=()=>{if(!guard.current)setOpen(false)};const move=()=>{if(!tryAcquirePending(guard))return;start(async()=>{try{const r=await moveTrainerToGroup(trainerId,groupId||null);if(r.ok){setOpen(false);router.refresh()}else setError(r.message)}catch{setError("Не удалось переместить тренажёр.")}finally{releasePending(guard)}})};return <><button className={styles.create} onClick={()=>setOpen(true)}>Тема</button>{open&&<Dialog title={`Переместить «${title}»`} close={close} pending={pending}><label>Тема<select value={groupId} disabled={pending} onChange={e=>setGroupId(e.target.value)}><option value="">Без темы</option>{groups.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label>{error&&<p className={styles.error} role="alert">{error}</p>}<footer><button disabled={pending} onClick={close}>Отмена</button><button className={styles.primary} disabled={pending} onClick={move}>{pending?"Перемещаем…":"Переместить"}</button></footer></Dialog>}</>}
