"use server";

import { revalidatePath } from "next/cache";
import { getCurrentProfile } from "@/lib/auth/get-current-profile";
import { createAdminClient } from "@/lib/supabase/admin";
import type {TrainerGroupType} from "@/lib/trainers/trainer-groups";

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export type GroupActionResult={ok:boolean;message:string};
async function context(){const current=await getCurrentProfile();return current?.profile?.role==="ADMIN"?{adminId:current.profile.id,db:createAdminClient()}:null;}
function refresh(){revalidatePath("/admin/trainers/quick-problems");revalidatePath("/admin/trainers/theory");}
function status(data:unknown){return data&&typeof data==="object"&&"status" in data?String((data as {status:unknown}).status):"";}
export async function createTrainerGroup(trainerType:TrainerGroupType,title:string):Promise<GroupActionResult>{const ctx=await context();if(!ctx)return{ok:false,message:"Недостаточно прав."};const r=await ctx.db.rpc("create_trainer_group_atomic",{p_owner_admin_id:ctx.adminId,p_trainer_type:trainerType,p_title:title});const s=status(r.data);if(r.error)return{ok:false,message:"Не удалось создать тему."};if(s==="duplicate")return{ok:false,message:"Тема с таким названием уже существует."};if(s!=="created")return{ok:false,message:"Введите название от 1 до 120 символов."};refresh();return{ok:true,message:"Тема создана."};}
export async function renameTrainerGroup(id:string,trainerType:TrainerGroupType,title:string):Promise<GroupActionResult>{const ctx=await context();if(!ctx||!uuid.test(id))return{ok:false,message:"Тема недоступна."};const r=await ctx.db.rpc("rename_trainer_group_atomic",{p_owner_admin_id:ctx.adminId,p_group_id:id,p_trainer_type:trainerType,p_title:title});const s=status(r.data);if(r.error)return{ok:false,message:"Не удалось переименовать тему."};if(s==="duplicate")return{ok:false,message:"Тема с таким названием уже существует."};if(s!=="renamed")return{ok:false,message:"Тема недоступна или название некорректно."};refresh();return{ok:true,message:"Тема переименована."};}
export async function deleteTrainerGroup(id:string,trainerType:TrainerGroupType):Promise<GroupActionResult>{const ctx=await context();if(!ctx||!uuid.test(id))return{ok:false,message:"Тема недоступна."};const r=await ctx.db.rpc("delete_trainer_group_atomic",{p_owner_admin_id:ctx.adminId,p_group_id:id,p_trainer_type:trainerType});if(r.error||status(r.data)!=="deleted")return{ok:false,message:"Не удалось удалить тему."};refresh();return{ok:true,message:"Тема удалена. Тренажёры перемещены в «Без темы»."};}
export async function moveTrainerToGroup(trainerId:string,groupId:string|null):Promise<GroupActionResult>{const ctx=await context();if(!ctx||!uuid.test(trainerId)||(groupId!==null&&!uuid.test(groupId)))return{ok:false,message:"Некорректные данные."};const r=await ctx.db.rpc("move_trainer_to_group_atomic",{p_owner_admin_id:ctx.adminId,p_trainer_id:trainerId,p_group_id:groupId});if(r.error||status(r.data)!=="moved")return{ok:false,message:"Не удалось поменять тему."};refresh();return{ok:true,message:"Тема тренажёра изменена."};}
export async function moveTrainerGroup(id:string,trainerType:TrainerGroupType,direction:-1|1):Promise<GroupActionResult>{const ctx=await context();if(!ctx||!uuid.test(id)||(direction!==-1&&direction!==1))return{ok:false,message:"Некорректные данные."};const r=await ctx.db.rpc("move_trainer_group_atomic",{p_owner_admin_id:ctx.adminId,p_group_id:id,p_trainer_type:trainerType,p_direction:direction});if(r.error||status(r.data)!=="moved")return{ok:false,message:"Не удалось изменить порядок тем."};refresh();return{ok:true,message:"Порядок тем сохранён."};}
