"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { getCurrentProfile } from "@/lib/auth/get-current-profile";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { createStudentAvatarUrl, studentAvatarBucket } from "@/lib/avatars/student-avatar";

const categories=["PAGE","MATERIAL","TEST","DATA","OTHER"] as const;
const avatarMaxSize=5*1024*1024;
function avatarOperation(){return crypto.randomUUID()}
function logAvatar(stage:string,operation:string){console.error(stage,{operation})}
async function isWebP(file:File){if(file.type!=="image/webp"||file.size===0||file.size>avatarMaxSize)return false;const bytes=new Uint8Array(await file.slice(0,12).arrayBuffer());return bytes.length===12&&String.fromCharCode(...bytes.slice(0,4))==="RIFF"&&String.fromCharCode(...bytes.slice(8,12))==="WEBP"}
function refreshAvatarViews(){revalidatePath("/student","layout");revalidatePath("/admin/students","layout")}
export type SupportActionState={ok:boolean;message:string};
export async function sendSupportMessage(_:SupportActionState,data:FormData):Promise<SupportActionState>{const current=await getCurrentProfile();if(!current||current.profile?.role!=="STUDENT"||current.profile.student_status!=="ACTIVE")return{ok:false,message:"Недостаточно прав."};const category=String(data.get("category")??"");const message=String(data.get("message")??"").trim();if(!categories.includes(category as typeof categories[number])||message.length<10||message.length>2000)return{ok:false,message:"Проверьте категорию и сообщение от 10 до 2000 символов."};const result=await createAdminClient().rpc("create_support_message_rate_limited",{p_student_id:current.user.id,p_category:category,p_message:message});if(result.error){console.error("SUPPORT_INSERT",{code:result.error.code,message:result.error.message});return{ok:false,message:"Не удалось отправить сообщение. Попробуйте ещё раз."}}const status=(result.data as {status?:string}|null)?.status;if(status==="rate_limited")return{ok:false,message:"Подождите 30 секунд перед следующим сообщением."};if(status!=="created")return{ok:false,message:"Не удалось отправить сообщение. Попробуйте ещё раз."};return{ok:true,message:"Сообщение отправлено."}}
export async function signOutToHome(){const supabase=await createClient({requireCookieWrites:true});await supabase.auth.signOut({scope:"local"});redirect("/")}
export async function uploadCurrentStudentAvatar(data:FormData){const current=await getCurrentProfile();if(!current||current.profile?.role!=="STUDENT"||current.profile.student_status!=="ACTIVE")return{ok:false,message:"Недостаточно прав.",url:null};const file=data.get("avatar");if(!(file instanceof File)||!(await isWebP(file)))return{ok:false,message:"Загрузите обработанное изображение WebP размером до 5 МБ.",url:null};const operation=avatarOperation(),admin=createAdminClient(),oldPath=current.profile.avatar_path,path=`students/${current.user.id}/avatar-${crypto.randomUUID()}.webp`;const uploaded=await admin.storage.from(studentAvatarBucket).upload(path,file,{upsert:false,contentType:"image/webp",cacheControl:"3600"});if(uploaded.error){logAvatar("AVATAR_UPLOAD_STORAGE",operation);return{ok:false,message:"Не удалось загрузить изображение. Попробуйте ещё раз.",url:null}}const updated=await admin.from("profiles").update({avatar_path:path,avatar_updated_at:new Date().toISOString()}).eq("id",current.user.id).eq("role","STUDENT").select("id").maybeSingle();if(updated.error||!updated.data){logAvatar("AVATAR_UPLOAD_PROFILE",operation);const cleanup=await admin.storage.from(studentAvatarBucket).remove([path]);if(cleanup.error)logAvatar("AVATAR_UPLOAD_CLEANUP",operation);return{ok:false,message:"Не удалось обновить изображение. Предыдущее изображение сохранено.",url:null}}if(oldPath&&oldPath!==path){const removed=await admin.storage.from(studentAvatarBucket).remove([oldPath]);if(removed.error)logAvatar("AVATAR_UPLOAD_CLEANUP",operation)}refreshAvatarViews();return{ok:true,message:"Изображение обновлено.",url:await createStudentAvatarUrl(path)}}
export async function deleteCurrentStudentAvatar(){const current=await getCurrentProfile();if(!current||current.profile?.role!=="STUDENT"||current.profile.student_status!=="ACTIVE")return{ok:false,message:"Недостаточно прав."};const operation=avatarOperation(),admin=createAdminClient(),path=current.profile.avatar_path;const updated=await admin.from("profiles").update({avatar_path:null,avatar_updated_at:new Date().toISOString()}).eq("id",current.user.id).eq("role","STUDENT").select("id").maybeSingle();if(updated.error||!updated.data){logAvatar("AVATAR_DELETE_PROFILE",operation);return{ok:false,message:"Не удалось удалить изображение."}}if(path){const removed=await admin.storage.from(studentAvatarBucket).remove([path]);if(removed.error)logAvatar("AVATAR_DELETE_STORAGE",operation)}refreshAvatarViews();return{ok:true,message:"Изображение удалено."}}
