"use client";

import Link from "next/link";
import { usePathname, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useRef, useState, useTransition } from "react";
import { createDevPastLesson, deleteLessonHomework, deletePastLesson, saveLessonHomework, saveStudentSchedule, setFutureLessonStatus, setLessonAttendance } from "@/app/admin/students/[id]/lesson-actions";
import { lessonStatusLabels } from "@/lib/lessons/lesson-status";
import LessonActionsDropdown, { type LessonMenuAction } from "./lesson-actions-dropdown";
import type { ScheduleInput, ScheduleSlot, StudentLesson } from "./student-lesson-types";
import styles from "./student-lessons-panel.module.css";

const weekdays=["","Понедельник","Вторник","Среда","Четверг","Пятница","Суббота","Воскресенье"];
const zone="Asia/Almaty";
function dayTime(start:string,end:string){const date=new Intl.DateTimeFormat("ru-RU",{timeZone:zone,day:"numeric",month:"long",weekday:"long"}).format(new Date(start));const time=new Intl.DateTimeFormat("ru-RU",{timeZone:zone,hour:"2-digit",minute:"2-digit"});return`${date} · ${time.format(new Date(start))}–${time.format(new Date(end))}`;}
function addMinutes(time:string,minutes:number){const [h,m]=time.slice(0,5).split(":").map(Number),total=h*60+m+minutes;return`${String(Math.floor(total/60)%24).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`;}
type Modal={kind:"schedule"}|{kind:"future";lesson:StudentLesson;value:string}|{kind:"attendance";lesson:StudentLesson}|{kind:"homework";lesson:StudentLesson}|{kind:"devCreate"}|{kind:"delete";lesson:StudentLesson}|null;

export default function StudentLessonsPanel({studentId,schedule,upcoming,past,hasMore,loadError,isDevelopment}:{studentId:string;schedule:ScheduleSlot[];upcoming:StudentLesson[];past:StudentLesson[];hasMore:boolean;loadError?:string;isDevelopment:boolean}){
  const [modal,setModal]=useState<Modal>(null),[notice,setNotice]=useState(""),[error,setError]=useState("");const[pending,startTransition]=useTransition();const pathname=usePathname(),query=useSearchParams();const cancelRef=useRef<HTMLButtonElement>(null),modalRef=useRef<HTMLDivElement>(null);
  const initialSlots=useMemo<ScheduleInput[]>(()=>schedule.map(slot=>({weekday:slot.weekday,startTime:slot.startTime.slice(0,5),durationMinutes:slot.durationMinutes})),[schedule]);const[slots,setSlots]=useState(initialSlots);const[attendance,setAttendance]=useState("ATTENDED");
  useEffect(()=>{if(!notice)return;const timer=window.setTimeout(()=>setNotice(""),4000);return()=>window.clearTimeout(timer)},[notice]);
  useEffect(()=>{if(!modal)return;requestAnimationFrame(()=>cancelRef.current?.focus());const previous=document.body.style.overflow;document.body.style.overflow="hidden";const key=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!pending)setModal(null);if(event.key!=="Tab"||!modalRef.current)return;const nodes=[...modalRef.current.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')];if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",key);return()=>{document.body.style.overflow=previous;document.removeEventListener("keydown",key)}},[modal,pending]);
  function close(){if(!pending){setModal(null);setError("");setSlots(initialSlots)}}
  function run(task:()=>Promise<{ok:boolean;message:string}>){setError("");startTransition(async()=>{const result=await task();if(!result.ok){setError(result.message);return}setModal(null);setNotice(result.message)})}
  function scheduleSubmit(event:React.FormEvent){event.preventDefault();if(!slots.length&&!window.confirm("Полностью очистить постоянное расписание?"))return;const data=new FormData();data.set("slots",JSON.stringify(slots));run(()=>saveStudentSchedule(studentId,data));}
  const more=new URLSearchParams(query.toString());more.set("tab","lessons");more.set("history",String(Math.floor(past.length/10)+1));
  return <section className={styles.panel}><div className={styles.scheduleHead}><div><h2>Расписание</h2>{schedule.length?<div className={styles.scheduleList}>{schedule.map(slot=><span key={slot.id}>{weekdays[slot.weekday]} · {slot.startTime.slice(0,5)}–{addMinutes(slot.startTime,slot.durationMinutes)}</span>)}</div>:<p>Постоянное расписание ещё не задано.</p>}</div><button type="button" onClick={()=>{setSlots(initialSlots);setModal({kind:"schedule"})}}>{schedule.length?"Изменить":"Настроить расписание"}</button></div>{isDevelopment&&<button className={styles.devButton} type="button" onClick={()=>setModal({kind:"devCreate"})}>Создать тестовый прошедший урок</button>}{notice&&<p className={styles.notice}>{notice}</p>}{loadError?<p className={styles.error}>{loadError}</p>:<>
    <LessonList title="Ближайшие уроки" lessons={upcoming} empty="Ближайших уроков пока нет." onFuture={(lesson,value)=>setModal({kind:"future",lesson,value})}/>
    <LessonList title="Прошедшие уроки" lessons={past} empty="Прошедших уроков пока нет." onAttendance={(lesson)=>{setAttendance(lesson.status==="NO_SHOW"?"NO_SHOW":lesson.status==="LATE_CANCELLED"?"LATE_CANCELLED":"ATTENDED");setModal({kind:"attendance",lesson})}} onHomework={(lesson)=>setModal({kind:"homework",lesson})} onDelete={(lesson)=>setModal({kind:"delete",lesson})}/>
    {hasMore&&<Link className={styles.more} href={`${pathname}?${more.toString()}`}>Показать ещё</Link>}
  </>}{modal&&<div className={styles.backdrop} onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><div ref={modalRef} className={styles.modal} role="dialog" aria-modal="true"><h2>{modal.kind==="schedule"?"Расписание":modal.kind==="attendance"?"Посещаемость":modal.kind==="homework"?"Домашнее задание":"Подтверждение"}</h2>
    {modal.kind==="schedule"&&<form onSubmit={scheduleSubmit}><div className={styles.slotList}>{slots.map((slot,index)=><div className={styles.slot} key={index}><select value={slot.weekday} onChange={e=>setSlots(rows=>rows.map((row,i)=>i===index?{...row,weekday:Number(e.target.value)}:row))}>{weekdays.slice(1).map((label,i)=><option value={i+1} key={label}>{label}</option>)}</select><input type="time" value={slot.startTime} required onChange={e=>setSlots(rows=>rows.map((row,i)=>i===index?{...row,startTime:e.target.value}:row))}/><input type="number" min={15} max={300} value={slot.durationMinutes} onChange={e=>setSlots(rows=>rows.map((row,i)=>i===index?{...row,durationMinutes:Number(e.target.value)}:row))}/><button type="button" onClick={()=>setSlots(rows=>rows.filter((_,i)=>i!==index))}>Удалить</button></div>)}</div><button className={styles.add} type="button" onClick={()=>setSlots(rows=>[...rows,{weekday:1,startTime:"18:00",durationMinutes:60}])}>Добавить день</button>{error&&<p className={styles.error}>{error}</p>}<Actions cancelRef={cancelRef} close={close} pending={pending}/></form>}
    {modal.kind==="future"&&<><p>{modal.value==="SCHEDULED"?`Вернуть урок ${dayTime(modal.lesson.startsAt,modal.lesson.endsAt)} в запланированные?`:`Отменить урок ${dayTime(modal.lesson.startsAt,modal.lesson.endsAt)}?`}</p>{error&&<p className={styles.error}>{error}</p>}<Actions cancelRef={cancelRef} close={close} pending={pending} submit={()=>run(()=>setFutureLessonStatus(studentId,modal.lesson.id,modal.value))}/></>}
    {modal.kind==="attendance"&&<>{modal.lesson.status.startsWith("CANCELLED")&&<p>Текущий статус: {lessonStatusLabels[modal.lesson.status]}</p>}<div className={styles.radios}>{[["ATTENDED","Посещение было"],["NO_SHOW","Не посещён"],["LATE_CANCELLED","Поздно отменён"]].map(([value,label])=><label key={value}><input type="radio" checked={attendance===value} onChange={()=>setAttendance(value)}/>{label}</label>)}</div>{error&&<p className={styles.error}>{error}</p>}<Actions cancelRef={cancelRef} close={close} pending={pending} submit={()=>run(()=>setLessonAttendance(studentId,modal.lesson.id,attendance))}/></>}
    {modal.kind==="homework"&&<HomeworkForm lesson={modal.lesson} error={error} pending={pending} cancelRef={cancelRef} close={close} save={(data)=>run(()=>saveLessonHomework(studentId,modal.lesson.id,data))} remove={()=>{if(window.confirm("Удалить запись домашнего задания?"))run(()=>deleteLessonHomework(studentId,modal.lesson.id))}}/>}
    {modal.kind==="devCreate"&&<><p>Создать тестовый урок, завершившийся вчера?</p>{error&&<p className={styles.error}>{error}</p>}<Actions cancelRef={cancelRef} close={close} pending={pending} submit={()=>run(()=>createDevPastLesson(studentId))} submitLabel="Создать"/></>}
    {modal.kind==="delete"&&<><p>Удалить урок за {dayTime(modal.lesson.startsAt,modal.lesson.endsAt)}? Вместе с ним будет удалена связанная запись ДЗ.</p>{error&&<p className={styles.error}>{error}</p>}<Actions cancelRef={cancelRef} close={close} pending={pending} submit={()=>run(()=>deletePastLesson(studentId,modal.lesson.id))} submitLabel="Удалить урок"/></>}
  </div></div>}</section>
}
function Actions({cancelRef,close,pending,submit,submitLabel="Сохранить"}:{cancelRef:React.RefObject<HTMLButtonElement|null>;close:()=>void;pending:boolean;submit?:()=>void;submitLabel?:string}){return<div className={styles.actions}><button ref={cancelRef} type="button" onClick={close} disabled={pending}>Отмена</button><button type={submit?"button":"submit"} onClick={submit} disabled={pending}>{pending?"Сохраняем…":submitLabel}</button></div>}
function HomeworkForm({lesson,error,pending,cancelRef,close,save,remove}:{lesson:StudentLesson;error:string;pending:boolean;cancelRef:React.RefObject<HTMLButtonElement|null>;close:()=>void;save:(data:FormData)=>void;remove:()=>void}){return<form onSubmit={event=>{event.preventDefault();save(new FormData(event.currentTarget))}} className={styles.homework}><label>Название<input name="title" maxLength={200} required defaultValue={lesson.homework?.title??""}/></label><label>Оценка<select name="grade" defaultValue={lesson.homework?.grade??""}><option value="">Без оценки</option>{Array.from({length:11},(_,i)=><option key={i} value={i}>{i}</option>)}</select></label><label>Комментарий<textarea name="comment" maxLength={500} defaultValue={lesson.homework?.comment??""}/></label>{error&&<p className={styles.error}>{error}</p>}{lesson.homework&&<button className={styles.removeHomework} type="button" onClick={remove} disabled={pending}>Удалить запись</button>}<Actions cancelRef={cancelRef} close={close} pending={pending}/></form>}
function LessonList({title,lessons,empty,onFuture,onAttendance,onHomework,onDelete}:{title:string;lessons:StudentLesson[];empty:string;onFuture?:(lesson:StudentLesson,value:string)=>void;onAttendance?:(lesson:StudentLesson)=>void;onHomework?:(lesson:StudentLesson)=>void;onDelete?:(lesson:StudentLesson)=>void}){
  return <section className={styles.lessonSection}><h3>{title}</h3>{lessons.length?<div className={styles.lessons}>{lessons.map(lesson=>{
    const actions:LessonMenuAction[]=[];
    if(onFuture){
      if(lesson.status!=="CANCELLED_BY_TEACHER")actions.push({label:"Отменён преподавателем",onSelect:()=>onFuture(lesson,"CANCELLED_BY_TEACHER")});
      if(lesson.status!=="CANCELLED_BY_STUDENT")actions.push({label:"Отменён учеником",onSelect:()=>onFuture(lesson,"CANCELLED_BY_STUDENT")});
      if(lesson.status!=="SCHEDULED")actions.push({label:"Вернуть в запланированные",onSelect:()=>onFuture(lesson,"SCHEDULED")});
    }
    if(onAttendance)actions.push({label:"Изменить посещаемость",onSelect:()=>onAttendance(lesson)});
    if(onHomework)actions.push({label:"Домашнее задание",onSelect:()=>onHomework(lesson)});
    if(onDelete)actions.push({label:"Удалить урок",onSelect:()=>onDelete(lesson),danger:true});
    return <article className={`${styles.lesson} ${lesson.status.startsWith("CANCELLED")?styles.muted:""}`} key={lesson.id}><div><strong>{dayTime(lesson.startsAt,lesson.endsAt)}</strong><span className={`${styles.badge} ${styles[lesson.status.toLowerCase()]}`}>{lessonStatusLabels[lesson.status]}</span>{onHomework&&<small>{lesson.homework?lesson.homework.grade===null?"ДЗ без оценки":`ДЗ ${lesson.homework.grade}/10`:"ДЗ —"}</small>}</div><LessonActionsDropdown actions={actions}/></article>;
  })}</div>:<p className={styles.empty}>{empty}</p>}</section>;
}
