"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState, useTransition } from "react";
import { grantMaterialAccess, grantMaterialFolderAccess, revokeMaterialAccess, revokeMaterialFolderAccess } from "@/app/admin/students/[id]/material-access-actions";
import type { MaterialLibraryFolder, MaterialLibraryItem, MaterialLibraryLevel, StudentFolderAccessItem, StudentMaterialAccessItem } from "./student-material-types";
import styles from "./student-material-access.module.css";

const typeLabels = { FILE: "Файл", LINK: "Ссылка", VIDEO: "Видео", TEXT: "Текст" } as const;
const typeIcons = { FILE: "F", LINK: "↗", VIDEO: "▶", TEXT: "T" } as const;
function date(value: string) { return new Intl.DateTimeFormat("ru-RU", { dateStyle: "medium" }).format(new Date(value)); }
function size(value: number | null) { if (value === null) return null; if (value >= 1024 ** 2) return `${(value / 1024 ** 2).toFixed(1)} МБ`; if (value >= 1024) return `${Math.round(value / 1024)} КБ`; return `${value} Б`; }
function actionLabel(item: MaterialLibraryItem) { return item.type === "FILE" ? "Открыть файл" : item.type === "LINK" ? "Открыть ссылку" : item.type === "VIDEO" ? "Смотреть видео" : "Открыть материал"; }

type Selection = { kind: "folder"; item: MaterialLibraryFolder } | { kind: "material"; item: MaterialLibraryItem };

function AssignMaterialModal({ studentId, onClose, onSuccess, opener }: { studentId: string; onClose: () => void; onSuccess: (message: string) => void; opener: React.RefObject<HTMLButtonElement | null> }) {
  const [level, setLevel] = useState<MaterialLibraryLevel | null>(null); const [selection, setSelection] = useState<Selection | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [pending, startTransition] = useTransition(); const pendingRef = useRef(pending); const dialog = useRef<HTMLDivElement>(null);
  const load = useCallback(async (folderId: string | null) => { setLoading(true); setError(""); try { const response = await fetch(`/api/admin/material-library${folderId ? `?folderId=${encodeURIComponent(folderId)}` : ""}`, { cache: "no-store" }); const body = await response.json() as MaterialLibraryLevel & { message?: string }; if (!response.ok) throw new Error(body.message || "Не удалось загрузить библиотеку материалов."); setLevel(body); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось загрузить библиотеку материалов."); } finally { setLoading(false); } }, []);
  function close() { if (pending) return; onClose(); requestAnimationFrame(() => opener.current?.focus()); }
  useEffect(() => { pendingRef.current = pending; }, [pending]);
  useEffect(() => { queueMicrotask(() => void load(null)); const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; requestAnimationFrame(() => dialog.current?.querySelector<HTMLElement>("button, a")?.focus()); const keydown = (event: KeyboardEvent) => { if (event.key === "Escape" && !pendingRef.current) { onClose(); requestAnimationFrame(() => opener.current?.focus()); } if (event.key !== "Tab" || !dialog.current) return; const nodes = [...dialog.current.querySelectorAll<HTMLElement>('button:not(:disabled), a[href], input:not(:disabled)')]; if (!nodes.length) return; const first = nodes[0]; const last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener("keydown", keydown); return () => { document.body.style.overflow = previous; document.removeEventListener("keydown", keydown); }; }, [load, onClose, opener]);
  function assign() { if (!selection) return; setError(""); startTransition(async () => { const result = selection.kind === "folder" ? await grantMaterialFolderAccess(studentId, selection.item.id) : await grantMaterialAccess(studentId, selection.item.id); if (!result.ok) { setError(result.message); return; } onClose(); onSuccess(result.message); requestAnimationFrame(() => opener.current?.focus()); }); }
  return <div className={styles.backdrop} onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><div className={styles.modal} ref={dialog} role="dialog" aria-modal="true" aria-labelledby="material-modal-title"><header><div><span>Доступ к материалам</span><h2 id="material-modal-title">{selection ? "Подтверждение" : "Выберите материал или папку"}</h2></div><button type="button" onClick={close} disabled={pending} aria-label="Закрыть">×</button></header>
    {selection ? <div className={styles.confirm}><h3>{selection.kind === "folder" ? `Назначить папку “${selection.item.name}”?` : `Назначить материал “${selection.item.title}”?`}</h3><p>{selection.kind === "folder" ? "Ученик получит динамический доступ ко всем материалам внутри неё и вложенных папок. Новые материалы тоже будут появляться автоматически." : "Материал появится в списке доступных ученику материалов."}</p>{error && <p className={styles.error} role="alert">{error}</p>}<div className={styles.modalActions}><button type="button" className={styles.secondary} onClick={() => { setSelection(null); setError(""); }} disabled={pending}>Назад</button><button type="button" className={styles.primary} onClick={assign} disabled={pending}>{pending ? "Назначаем…" : "Назначить"}</button></div></div> : <div className={styles.browser}><nav aria-label="Путь к папке"><button type="button" onClick={() => void load(null)}>Материалы</button>{level?.breadcrumb.map((item, index) => <span key={item.id}><i aria-hidden>›</i>{index === level.breadcrumb.length - 1 ? <b>{item.name}</b> : <button type="button" onClick={() => void load(item.id)}>{item.name}</button>}</span>)}</nav>{loading && <p className={styles.state}>Загрузка…</p>}{error && <p className={styles.error} role="alert">{error}</p>}{!loading && !error && level && <>
      {!!level.folders.length && <section><h3>Папки</h3><div className={styles.folderGrid}>{level.folders.map((folder) => <article className={styles.folderCard} key={folder.id}><button type="button" className={styles.folderOpen} onClick={() => void load(folder.id)}><span aria-hidden>▰</span><div><b>{folder.name}</b><small>{folder.childFolderCount} папок · {folder.materialCount} материалов</small><em>Ученик получит доступ ко всему содержимому и вложенным папкам</em></div></button><button type="button" className={styles.folderAssign} onClick={() => setSelection({ kind: "folder", item: folder })}>Назначить папку</button></article>)}</div></section>}
      {!!level.materials.length && <section><h3>Материалы</h3><div className={styles.libraryList}>{level.materials.map((item) => <article className={styles.libraryCard} key={item.id}><span className={styles.icon} aria-hidden>{typeIcons[item.type]}</span><div><h4>{item.title}</h4>{item.description && <p>{item.description}</p>}<small>{typeLabels[item.type]}{item.type === "FILE" && size(item.fileSize) ? ` · ${size(item.fileSize)}` : ""} · {date(item.createdAt)}</small></div><div className={styles.libraryActions}><button type="button" onClick={() => setSelection({ kind: "material", item })}>Назначить</button>{item.openUrl && <Link href={item.openUrl} target={item.external ? "_blank" : undefined} rel={item.external ? "noopener noreferrer" : undefined}>{actionLabel(item)}</Link>}</div></article>)}</div></section>}
      {!level.folders.length && !level.materials.length && <p className={styles.state}>В этой папке пока ничего нет.</p>}
    </>}</div>}
  </div></div>;
}

function RevokeButton({ studentId, kind, accessId, name, onSuccess }: { studentId: string; kind: "folder" | "material"; accessId: string; name: string; onSuccess: (message: string) => void }) {
  const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [pending, startTransition] = useTransition(); const cancel = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (open) requestAnimationFrame(() => cancel.current?.focus()); const key = (event: KeyboardEvent) => { if (event.key === "Escape" && !pending) setOpen(false); }; document.addEventListener("keydown", key); return () => document.removeEventListener("keydown", key); }, [open, pending]);
  function revoke() { setError(""); startTransition(async () => { const result = kind === "folder" ? await revokeMaterialFolderAccess(studentId, accessId) : await revokeMaterialAccess(studentId, accessId); if (!result.ok) { setError(result.message); return; } setOpen(false); onSuccess(result.message); }); }
  return <><button type="button" className={styles.revoke} onClick={() => setOpen(true)}>Отозвать</button>{open && <div className={styles.backdrop} onMouseDown={(event) => { if (event.target === event.currentTarget && !pending) setOpen(false); }}><div className={styles.revokeModal} role="dialog" aria-modal="true" aria-labelledby={`revoke-${accessId}`}><h2 id={`revoke-${accessId}`}>Отозвать доступ?</h2><p>{kind === "folder" ? `Отозвать доступ к папке “${name}”? Ученик потеряет доступ ко всему её содержимому и вложенным папкам.` : `Отозвать доступ к материалу “${name}”?`}</p>{error && <p className={styles.error} role="alert">{error}</p>}<div className={styles.modalActions}><button ref={cancel} type="button" className={styles.secondary} onClick={() => setOpen(false)} disabled={pending}>Отмена</button><button type="button" className={styles.danger} onClick={revoke} disabled={pending}>{pending ? "Отзываем…" : "Отозвать"}</button></div></div></div>}</>;
}

export default function StudentMaterialAccessList({ studentId, folders, materials, loadError }: { studentId: string; folders: StudentFolderAccessItem[]; materials: StudentMaterialAccessItem[]; loadError?: string }) {
  const [open, setOpen] = useState(false); const [notice, setNotice] = useState(""); const opener = useRef<HTMLButtonElement>(null); const close = useCallback(() => setOpen(false), []); const success = useCallback((value: string) => { setOpen(false); setNotice(value); }, []);
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(""), 4000); return () => window.clearTimeout(timer); }, [notice]);
  return <section className={styles.panel} aria-labelledby="student-materials-title"><div className={styles.heading}><div><h2 id="student-materials-title">Материалы ученика</h2><p>Папочные и индивидуальные доступы</p></div><button ref={opener} type="button" className={styles.assign} onClick={() => setOpen(true)}>Назначить материал</button></div>{notice && <p className={styles.notice} role="status">{notice}</p>}{loadError ? <p className={styles.error}>{loadError}</p> : <>{!folders.length && !materials.length && <p className={styles.empty}>Ученику пока не назначены материалы.</p>}{!!folders.length && <section className={styles.accessSection}><h3>Доступ к папкам</h3><div className={styles.accessList}>{folders.map((item) => <article className={styles.accessCard} key={item.accessId}><span className={styles.folderIcon} aria-hidden>▰</span><div><h4>{item.name}</h4><p>Всё содержимое и вложенные папки</p><small>Назначено {date(item.createdAt)}</small></div><div className={styles.cardActions}><Link href={`/admin/materials/folders/${item.folderId}`}>Открыть</Link><RevokeButton studentId={studentId} kind="folder" accessId={item.accessId} name={item.name} onSuccess={success}/></div></article>)}</div></section>}{!!materials.length && <section className={styles.accessSection}><h3>Отдельные материалы</h3><div className={styles.accessList}>{materials.map((item) => <article className={styles.accessCard} key={item.accessId}><span className={styles.icon} aria-hidden>{typeIcons[item.type]}</span><div><h4>{item.title}</h4><p>{typeLabels[item.type]}{item.type === "FILE" && size(item.fileSize) ? ` · ${size(item.fileSize)}` : ""}</p><small>Назначено {date(item.grantedAt)}</small></div><div className={styles.cardActions}>{item.openUrl && <Link href={item.openUrl} target={item.external ? "_blank" : undefined} rel={item.external ? "noopener noreferrer" : undefined}>Открыть</Link>}<RevokeButton studentId={studentId} kind="material" accessId={item.accessId} name={item.title} onSuccess={success}/></div></article>)}</div></section>}</>}{open && <AssignMaterialModal studentId={studentId} onClose={close} onSuccess={success} opener={opener}/>}</section>;
}
